name: ai_chat_app
description: "AI Chat Cross Platform App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_flavorizr: ^2.4.0
  flutter_native_splash: ^2.4.6
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  # Supabase dependencies
  supabase_flutter: ^2.8.0

  # State management with Bloc
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7

  # Navigation
  go_router: ^15.2.0

  # Local storage
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1

  # File handling and storage
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  path: ^1.9.0
  mime: ^1.0.6

  # HTTP and networking
  dio: ^5.8.0+1

  # UI components
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  shimmer: ^3.0.0

  # Utilities
  uuid: ^4.5.1
  crypto: ^3.0.6
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/app_icon/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
